-- MySQL Script generated by MySQL Workbench
-- Mon Oct 18 21:02:21 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema sistemasdb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema sistemasdb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `sistemasdb` DEFAULT CHARACTER SET utf8 ;
USE `sistemasdb` ;

-- -----------------------------------------------------
-- Table `sistemasdb`.`cursos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistemasdb`.`cursos` (
  `nombre` VARCHAR(6) NOT NULL,
  `aclaracion` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`nombre`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = '	';


-- -----------------------------------------------------
-- Table `sistemasdb`.`alumnos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistemasdb`.`alumnos` (
  `dni` INT NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `apellido` VARCHAR(45) NOT NULL,
  `session_id` VARCHAR(45) NOT NULL,
  `nombre_curso` VARCHAR(6) NOT NULL,
  PRIMARY KEY (`dni`),
  INDEX `fk_alumnos_cursos_idx` (`nombre_curso` ASC) VISIBLE,
  CONSTRAINT `fk_alumnos_cursos`
    FOREIGN KEY (`nombre_curso`)
    REFERENCES `sistemasdb`.`cursos` (`nombre`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `sistemasdb`.`docentes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistemasdb`.`docentes` (
  `dni` INT NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `apellido` VARCHAR(45) NOT NULL,
  `session_id` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`dni`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `sistemasdb`.`modulos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistemasdb`.`modulos` (
  `id` INT NOT NULL,
  `dia` INT NOT NULL,
  `hora_inicio` TIME NOT NULL,
  `hora_final` TIME NOT NULL,
  `fecha` DATE NULL DEFAULT NULL,
  `nombre_curso` VARCHAR(6) NOT NULL,
  `dni_docente` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_modulos_cursos1_idx` (`nombre_curso` ASC) VISIBLE,
  INDEX `fk_modulos_docentes1_idx` (`dni_docente` ASC) VISIBLE,
  CONSTRAINT `fk_modulos_cursos1`
    FOREIGN KEY (`nombre_curso`)
    REFERENCES `sistemasdb`.`cursos` (`nombre`),
  CONSTRAINT `fk_modulos_docentes1`
    FOREIGN KEY (`dni_docente`)
    REFERENCES `sistemasdb`.`docentes` (`dni`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `sistemasdb`.`presentismo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistemasdb`.`presentismo` (
  `id_modulo` INT NOT NULL,
  `dni_alumno` INT NOT NULL,
  `fecha` DATE NOT NULL,
  `presente` TINYINT NOT NULL,
  `nota` VARCHAR(45) NULL,
  INDEX `fk_presentismo_alumnos1_idx` (`dni_alumno` ASC) VISIBLE,
  INDEX `fk_presentismo_modulos1_idx` (`id_modulo` ASC) VISIBLE,
  CONSTRAINT `fk_presentismo_alumnos1`
    FOREIGN KEY (`dni_alumno`)
    REFERENCES `sistemasdb`.`alumnos` (`dni`),
  CONSTRAINT `fk_presentismo_modulos1`
    FOREIGN KEY (`id_modulo`)
    REFERENCES `sistemasdb`.`modulos` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
